services:
  multipaper-master:
    restart: always
    image: multipaper-master:0.0.1
    build: Multipaper-master-database/.
    volumes:
      - master:/app
    ports:
      - "35353:35353"
      - "25565:25565"
    networks:
      - multipaper-networking

  multipaper-server:
    restart: always
    image: multipaper-server:0.0.1
    build: Multipaper-server/.
    networks:
      - multipaper-networking
    depends_on:
      - multipaper-master

networks:
  multipaper-networking:
    name: multipaper-networking
    driver: bridge
    external: true

volumes:
  master: